SELECT
    ALL_CONSTRAINTS.CONSTRAINT_NAME as ForeignKey,
    ALL_CONSTRAINTS.TABLE_NAME as TableName,
    L_Collumns.COLUMN_NAME as Collumn,
    ALL_CONSTRAINTS.R_CONSTRAINT_NAME as References_Constraint,
    R_Collumns.COLUMN_NAME as References_Collumn,
    R_Collumns.TABLE_NAME as References_Table
FROM
    ALL_CONSTRAINTS
LEFT JOIN ALL_CONS_COLUMNS R_Collumns ON R_Collumns.CONSTRAINT_NAME = ALL_CONSTRAINTS.R_CONSTRAINT_NAME
LEFT JOIN ALL_CONS_COLUMNS L_Collumns ON L_Collumns.CONSTRAINT_NAME = ALL_CONSTRAINTS.CONSTRAINT_NAME
WHERE
    ALL_CONSTRAINTS.OWNER = 'CHINOOK' AND
    ALL_CONSTRAINTS.CONSTRAINT_TYPE = 'R';